server:
  port: 9999
spring:
  liquibase:
    change-log: classpath:/db/changelog/base-db-changelog.xml
  profiles:
    active: postgres

logging:
  level:
    org:
      springframework:
        web: debug

